/* eslint-disable react/prop-types */

const BookDetails = ({books, genre}) =>{
  const filteredBook = books.filter((book) => book.genre === genre);

  const booklisting = filteredBook.map((book)=>(
    <div key={book.id}>
      <h2>Title: {book.title}</h2>
      <p>genre: {book.genre}</p>
    </div>
  ))
  return(
    <>
    <h1>Book Details</h1>
    {booklisting}
    </>
  )
}

const UserDetails = ({users, role}) =>{
  const filterUsers = users.filter((user) => user.role ===role);

  console.log(filterUsers)

  const userlisting = filterUsers.map((user)=>(
    <div key={user.id}>
      <h2>Name: {user.name}</h2>
      <p>Role: {user.role}</p>
    </div>
  ))

  return(
    <>
      <h1>User Details</h1>
      {userlisting}
    </>
  )
}

const ProductDetails = ({products , price})=>{
  const filterProducts = products.filter((product) => product.price > price);

  const productListing = filterProducts.map((product)=>(
    <div key={product.id}>
    <h2>Name: {product.name}</h2>
    <p>Price: {product.price}</p>
    <p>features: {product.features.color} {product.features.isWaterProof ? "Water proof" : "Water resistant"}</p>
    </div>
  ))

  return(
    <>
<h1>Product Listing</h1>
{
  productListing
}
    </>
  )
}

const CityDetails = ({cities, population}) =>{
  const filterCities = cities.filter((city)=>city.population > population);

  const cityListing = filterCities.map((city)=>(
    <div key={city.id}>
      <h2>Name: {city.name}</h2>
      <p>Population: {city.population}</p>
    </div>
  ))

  return(
    <>
      <h1>City Details</h1>
      {cityListing}
    </>
  )
}

const MovieDetails = ({movies ,releaseYear}) =>{
  const filteredMovies = movies.filter((movie) => movie.releaseYear > releaseYear);

  const movieListing = filteredMovies.map((movie)=>(
    <div key={movie.id}>
      <h2>Title: {movie.title}</h2>
      <p>ReleaseYear: {movie.releaseYear}</p>
    </div>
  ))
  return(
    <>
      <h1>Movie Details</h1>
      {movieListing}
    </>
  )
}

const PodcastDetails = ({podcasts})=>{
  const filterPodcast = podcasts.filter((podcast) => podcast.featured);

  const podcastListing = filterPodcast.map((podcast)=>(
    <div key={podcast.id}>
      <h2>Title: {podcast.title}</h2>
      <p>hosts: {podcast.host.join(", ")}</p>
      <p>{podcast.featured ? "Featured" : "Not Featured"}</p>
    </div>
  ))

  return(
    <>
      <h1>Podcast Details</h1>
      {podcastListing}
    </>
  )
}

const Movies = ({movies , releaseYear}) =>{
  const filterMovies = movies.filter((movie) => movie.releaseYear >= releaseYear);

  const totalDuration = filterMovies.reduce((total,movie)=> total + movie.duration , 0);

  const averageRating = totalDuration / movies.length;

  return(
    <>
      <h1>Average Duration of Movies above 2000</h1>
      {averageRating.toFixed(2)}
    </>
  )
}

const TaskDetails = ({tasks})=>{
  const filterTask = tasks.filter((task)=>task.completed);


  return(
    <>
      <h1>Total Number of Completd Task </h1>
      {filterTask.length}
    </>
  )
}

const VehicleDetails = ({vehicles}) =>{
  const totalDistance = vehicles.reduce((total,vehicle) => total + vehicle.distance , 0);

  return(
    <>
      <h1>Total Distance travel by vehicles</h1>
      {totalDistance}
    </>
  )
}

const SalesDetails = ({sales}) =>{
  const total = sales.reduce((total,product)=> total + product.price * product.quantity , 0);

  return(
    <>
      <h1>Total revenue generated by all sales transactions.</h1>
      {total}
    </>
  )
}

const App = () => {
  const books = [

    { id: 1, title: "Dune", genre: "Science Fiction" },
  
    { id: 2, title: "Neuromancer", genre: "Science Fiction" },
  
    { id: 3, title: "Foundation", genre: "Sci-fi" },
  
  ];

  const users = [

    { id: 1, name: "Alice", role: "User" },
  
    { id: 2, name: "Bob", role: "Admin" },
  
    { id: 3, name: "Charlie", role: "User" },
  
    { id: 4, name: "John", role: "Admin" },
  
  ];

  const products = [

    { id: 1, name: "Laptop", price: 1200, features: {color: "green", isWaterProof: false} },
  
    { id: 2, name: "Smartphone", price: 800, features: {color: "blue", isWaterProof: true} },
  
    { id: 3, name: "Headphones", price: 150, features: {color: "silver", isWaterProof: false} },
  
  ];

  const cities = [

    { id: 1, name: "New York", population: 8500000 },
  
    { id: 2, name: "Los Angeles", population: 539900 },
  
    { id: 3, name: "Chicago", population: 2700000 },
  
  ];

  const movies = [

    { id: 1, title: "Inception", releaseYear: 2010 },
  
    { id: 2, title: "La La Land", releaseYear: 2016 },
  
    { id: 3, title: "Interstellar", releaseYear: 2014 },
  
    { id: 4, title: "Dune 2", releaseYear: 2024 },
  
  ];

  const podcasts = [

    { id: 1, title: "Tech Talk", host: ["host 1"], featured: true },
  
    { id: 2, title: "Business Insights", host: ["host 2"], featured: false },
  
    { id: 3, title: "Science Hour", host: ["host 3", "host 4"], featured: true },
  
  ];
  
  const movies2 = [

    { id: 1, title: "The Matrix", duration: 136, releaseYear: 1999 },
  
    { id: 2, title: "Inception", duration: 148, releaseYear: 2010 },
  
    { id: 3, title: "Avatar", duration: 162, releaseYear: 2009 },
  
  ];
  
  const tasks = [

    { id: 1, description: "Complete project proposal", completed: true },
  
    { id: 2, description: "Review client feedback", completed: false },
  
    { id: 3, description: "Submit final report", completed: true },
  
  ];

  const vehicles = [

    { id: 1, name: "Car", distance: 150 },
  
    { id: 2, name: "Bicycle", distance: 10 },
  
    { id: 3, name: "Motorcycle", distance: 75 },
  
  ];

  const sales = [

    { id: 1, product: "Widget A", price: 25, quantity: 10 },
  
    { id: 2, product: "Gadget B", price: 50, quantity: 5 },
  
    { id: 3, product: "Tool C", price: 30, quantity: 8 },
  
  ];
  
  
  return (
    <>
    <BookDetails books={books}  genre={"Science Fiction"}/>
    <hr />
    <UserDetails users={users}  role="Admin"/>
    <hr />
    <ProductDetails products={products}  price={100}/>
    <hr />
    <CityDetails cities={cities}  population={1000000}/>
    <hr />
    <MovieDetails movies={movies}  releaseYear={2015}/>
    <hr />
    <PodcastDetails podcasts={podcasts} />
    <hr />
    <Movies movies={movies2}  releaseYear={2000}/>
    <hr />
    <TaskDetails tasks={tasks} />
    <hr />
    <VehicleDetails vehicles={vehicles} />
    <hr />
    <SalesDetails sales={sales} />
    </>
  )
}

export default App
